### ISSUE TITLE
Update commands from node 16 to node 20 

### ISSUE THREAD

**Issue by NinaHerrmann** [Opencast-Moodle/moodle-workflows-opencast#4]
When currently running ci workflows, the following warning is displayed:

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

The corresponding commands in the CI pipeline need to be updated.

**Comment by ferishili** [comment]
Completed in https://github.com/Opencast-Moodle/moodle-workflows-opencast/commit/edb6b605ff9f0a4864bc16adb361839f98d64122
