### ISSUE TITLE
Revert #6 and #8 once Node.js download is fixed

### ISSUE THREAD

**Issue by mtneug** [Opencast-Moodle/moodle-workflows-opencast#7]
This is to keep track of reverting #6 and #8 once upstream changes were made.

**Comment by abias** [comment]
Just a heads-up for you:
The upstream changes are there, you can revert these workarounds now @mtneug @ferishili

**Comment by ferishili** [comment]
Hi everyone,
FYI: I am going to start reverting the PRs
Maybe @bluetom should also be notified about this!
BR

**Comment by ferishili** [comment]
Close as completed in #9 and #10
